'use client'
import {useMemo,useState} from 'react'
import {AnimatePresence,motion} from 'framer-motion'
import {Search,UserRound,Heart,ShoppingBag,X,ArrowUpRight,ChevronDown,Minus,Plus,Menu} from 'lucide-react'

type Product={id:string;name:string;category:'Watches'|'Bags'|'Fragrance';gender?:'Men'|'Women';price:number;collection:string;description:string;image:string;secondary:string;details:string[]}
const IMG={watch1:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1200&q=85',watch2:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=85',watch3:'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=85',watch4:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1200&q=85',bag1:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',bag2:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=85',bag3:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1200&q=85',frag1:'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=85',frag2:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=85',hero:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=2200&q=90'}
const products:Product[]=[
{id:'nocturne',name:'Nocturne 01',category:'Watches',gender:'Men',price:2480,collection:'Signature',description:'A disciplined silhouette in polished steel, designed around presence.',image:IMG.watch1,secondary:IMG.watch2,details:['Automatic movement','316L stainless steel','42 mm case','Sapphire crystal','100 m water resistance']},
{id:'meridian',name:'Meridian 36',category:'Watches',gender:'Women',price:2190,collection:'Signature',description:'A refined study of proportion, light and restraint.',image:IMG.watch3,secondary:IMG.watch4,details:['Quartz movement','Polished steel','36 mm case','Sapphire crystal','50 m water resistance']},
{id:'atelier',name:'Atelier 42',category:'Watches',gender:'Men',price:2750,collection:'New Arrivals',description:'Architectural precision with a quietly expressive dial.',image:IMG.watch4,secondary:IMG.watch1,details:['Automatic movement','Brushed steel','42 mm case','Sapphire crystal','100 m water resistance']},
{id:'linea',name:'Linea 34',category:'Watches',gender:'Women',price:2320,collection:'New Arrivals',description:'Fine lines, considered materials, enduring elegance.',image:IMG.watch2,secondary:IMG.watch3,details:['Automatic movement','Steel case','34 mm case','Sapphire crystal','50 m water resistance']},
{id:'forma',name:'Forma Tote',category:'Bags',price:890,collection:'Everyday',description:'A structured everyday companion with a generous interior.',image:IMG.bag1,secondary:IMG.bag2,details:['Italian leather','Cotton lining','34 × 28 × 14 cm','Brushed hardware','Care card included']},
{id:'arc',name:'Arc Shoulder',category:'Bags',price:760,collection:'Shoulder Bags',description:'A sculptural shoulder bag built around a clean, continuous curve.',image:IMG.bag2,secondary:IMG.bag3,details:['Full-grain leather','Microfiber lining','24 × 17 × 8 cm','Adjustable strap','Care card included']},
{id:'voyage',name:'Voyage 48',category:'Bags',price:1240,collection:'Travel',description:'A generous travel silhouette made to move with purpose.',image:IMG.bag3,secondary:IMG.bag1,details:['Full-grain leather','Canvas lining','48 × 32 × 21 cm','Brushed hardware','Luggage sleeve']},
{id:'presence',name:'Presence Eau de Parfum',category:'Fragrance',price:165,collection:'Signature',description:'An atmospheric composition of cedar, iris and warm skin.',image:IMG.frag1,secondary:IMG.frag2,details:['50 ml Eau de Parfum','Woody floral','Top: bergamot','Heart: iris','Base: cedar & musk']},
{id:'afterlight',name:'Afterlight Eau de Parfum',category:'Fragrance',price:185,collection:'Eau de Parfum',description:'A lingering study in amber, spice and quiet warmth.',image:IMG.frag2,secondary:IMG.frag1,details:['75 ml Eau de Parfum','Amber woody','Top: pink pepper','Heart: incense','Base: amber & vetiver']}
]
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)

export default function Home(){
 const [menu,setMenu]=useState<string|null>(null),[search,setSearch]=useState(false),[bagOpen,setBagOpen]=useState(false),[wishlist,setWishlist]=useState<string[]>([]),[bag,setBag]=useState<string[]>([]),[quick,setQuick]=useState<Product|null>(null),[view,setView]=useState<'home'|'watches'|'bags'|'fragrance'|'about'>('home'),[filter,setFilter]=useState('All'),[query,setQuery]=useState('')
 const visible=useMemo(()=>products.filter(p=>(filter==='All'||p.category===filter||p.gender===filter)&&p.name.toLowerCase().includes(query.toLowerCase())),[filter,query])
 const add=(p:Product)=>{setBag(b=>[...b,p.id]);setBagOpen(true)}
 const go=(v:'home'|'watches'|'bags'|'fragrance'|'about')=>{setView(v);setMenu(null);window.scrollTo({top:0,behavior:'smooth'})}
 return <main className="min-h-screen bg-[#f4f1ea]">
 <header className="fixed top-0 left-0 right-0 z-40"><div className="mx-auto flex h-[76px] items-center justify-between px-6 md:px-10 transition-all bg-[#f4f1ea]/80 backdrop-blur-xl border-b border-black/10">
 <nav className="hidden md:flex gap-7 text-[10px] tracking-[.22em]"><button onClick={()=>{setMenu(menu==='Watches'?null:'Watches')}}>WATCHES</button><button onClick={()=>{setMenu(menu==='Bags'?null:'Bags')}}>BAGS</button><button onClick={()=>{setMenu(menu==='Fragrance'?null:'Fragrance')}}>FRAGRANCE</button></nav>
 <button onClick={()=>go('home')} className="absolute left-1/2 -translate-x-1/2 text-[13px] tracking-[.35em] whitespace-nowrap">RESPECT COLLECTION</button>
 <div className="flex items-center gap-4 ml-auto"><button aria-label="Search" onClick={()=>setSearch(true)}><Search size={17}/></button><button className="hidden sm:block" aria-label="Account"><UserRound size={17}/></button><button onClick={()=>setWishlist(wishlist.length?[]:products.slice(0,2).map(p=>p.id))} aria-label="Wishlist"><Heart size={17} fill={wishlist.length?'currentColor':'none'}/></button><button onClick={()=>setBagOpen(true)} className="relative" aria-label="Shopping bag"><ShoppingBag size={17}/>{bag.length>0&&<span className="absolute -right-2 -top-2 text-[8px]">{bag.length}</span>}</button><button className="md:hidden" onClick={()=>setMenu(menu==='mobile'?null:'mobile')}><Menu size={19}/></button></div></div>
 {menu&&menu!=='mobile'&&<div className="absolute left-0 right-0 top-[76px] border-b border-black/10 bg-[#f4f1ea] px-8 py-10"><div className="grid md:grid-cols-[1fr_1fr_280px] gap-8 max-w-6xl mx-auto"><div><p className="text-[9px] tracking-[.25em] text-black/45 mb-5">{menu.toUpperCase()}</p>{(menu==='Watches'?['MEN','WOMEN','NEW ARRIVALS','SIGNATURE']:menu==='Bags'?['HANDBAGS','SHOULDER BAGS','CROSSBODY','TRAVEL']:['SIGNATURE','EAU DE PARFUM','DISCOVERY']).map(x=><button key={x} onClick={()=>go(menu==='Watches'?'watches':menu==='Bags'?'bags':'fragrance')} className="block serif text-2xl md:text-3xl mb-2 hover:italic transition">{x}</button>)}</div><div className="hidden md:block image-wrap aspect-[4/3]"><img src={menu==='Watches'?IMG.watch1:menu==='Bags'?IMG.bag1:IMG.frag1} className="w-full h-full object-cover"/></div><div className="hidden md:flex flex-col justify-end text-[11px] leading-5 text-black/60">Considered design, refined materials and enduring presence.<button onClick={()=>go(menu==='Watches'?'watches':menu==='Bags'?'bags':'fragrance')} className="mt-5 underline underline-offset-4 text-left text-black">Explore {menu}</button></div></div></div>}
 {menu==='mobile'&&<div className="absolute top-[76px] left-0 right-0 bg-[#f4f1ea] border-b border-black/10 p-7"><div className="flex flex-col gap-5 serif text-3xl"><button onClick={()=>go('watches')}>Watches</button><button onClick={()=>go('bags')}>Bags</button><button onClick={()=>go('fragrance')}>Fragrance</button><button onClick={()=>go('about')}>About</button></div></div>}
 </header>
 {view==='home'&&<><section className="relative min-h-[92vh] flex items-end overflow-hidden"><img src={IMG.hero} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-black/35"/><div className="relative z-10 text-white px-6 md:px-12 pb-16 md:pb-20 max-w-3xl fade-up"><p className="text-[10px] tracking-[.32em] mb-5">RESPECT COLLECTION</p><h1 className="serif italic text-6xl md:text-8xl leading-[.9]">DEFINED BY<br/>PRESENCE.</h1><p className="mt-7 max-w-md text-sm text-white/80 leading-6">A study in modern luxury, crafted for those who leave an impression.</p><div className="mt-8 flex gap-6 text-[10px] tracking-[.2em]"><button onClick={()=>go('watches')} className="border border-white/60 px-6 py-4 hover:bg-white hover:text-black transition">EXPLORE COLLECTION</button><button onClick={()=>go('about')} className="px-2 py-4 border-b border-white/60">DISCOVER RESPECT</button></div></div></section>
 <section className="px-6 md:px-12 py-32 md:py-44 text-center"><p className="text-[9px] tracking-[.28em] text-black/45">THE HOUSE</p><h2 className="serif text-5xl md:text-7xl mt-6">LUXURY WITHOUT EXCESS.</h2><p className="max-w-xl mx-auto mt-8 text-sm leading-7 text-black/60">RESPECT COLLECTION is built around considered design, refined materials and enduring presence.</p></section>
 <Category img={IMG.watch2} title="TIME, REFINED." label="WATCHES" onClick={()=>go('watches')}/><Category img={IMG.bag1} title="CARRIED WITH PURPOSE." label="BAGS" reverse onClick={()=>go('bags')}/><Category img={IMG.frag1} title="A SIGNATURE THAT REMAINS." label="FRAGRANCE" onClick={()=>go('fragrance')}/>
 <section className="px-6 md:px-12 py-32 border-t border-black/10"><div className="flex justify-between items-end mb-10"><div><p className="text-[9px] tracking-[.28em] text-black/45">SELECTED OBJECTS</p><h2 className="serif text-4xl md:text-5xl mt-3">The edit.</h2></div><button onClick={()=>go('watches')} className="text-[10px] tracking-[.2em] border-b border-black pb-2">VIEW ALL</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p} wish={wishlist.includes(p.id)} onWish={()=>setWishlist(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])} onQuick={()=>setQuick(p)} onAdd={()=>add(p)}/>)}</div></section></>}
 {view!=='home'&&view!=='about'&&<Collection title={view==='watches'?'WATCHES':view==='bags'?'THE BAG COLLECTION':'THE SCENT OF RESPECT'} subtitle={view==='watches'?'Precision. Presence. Permanence.':view==='bags'?'Designed to be carried. Made to be remembered.':'A signature that stays after you leave.'} filter={filter} setFilter={setFilter} products={visible} onQuick={setQuick} onAdd={add} wishlist={wishlist} setWishlist={setWishlist} hero={view==='watches'?IMG.watch1:view==='bags'?IMG.bag2:IMG.frag1}/>} 
 {view==='about'&&<section className="pt-40"><div className="px-6 md:px-16 pb-28 max-w-6xl"><p className="text-[9px] tracking-[.3em] text-black/45">THE HOUSE</p><h1 className="serif text-7xl md:text-[10rem] leading-[.82] mt-8">RESPECT<br/>IS BUILT.</h1><p className="max-w-2xl mt-14 text-xl md:text-2xl leading-9 text-black/65">Design. Precision. Materials. Craftsmanship. Individuality. Timelessness.</p></div><div className="grid md:grid-cols-2"><img src={IMG.bag3} className="w-full aspect-square object-cover"/><div className="p-10 md:p-20 flex items-center"><p className="serif text-3xl md:text-5xl leading-tight">We believe luxury is felt in the decisions you do not need to announce.</p></div></div></section>}
 <footer className="mt-24 bg-[#11110f] text-[#f4f1ea] px-6 md:px-12 pt-20 pb-10"><div className="grid md:grid-cols-4 gap-12"><div className="md:col-span-2"><p className="text-sm tracking-[.32em]">RESPECT COLLECTION</p><p className="serif italic text-4xl mt-5">DEFINED BY PRESENCE.</p></div><div><p className="text-[9px] tracking-[.25em] opacity-50 mb-5">SHOP</p><button onClick={()=>go('watches')} className="block text-sm mb-2">Watches</button><button onClick={()=>go('bags')} className="block text-sm mb-2">Bags</button><button onClick={()=>go('fragrance')} className="block text-sm">Fragrance</button></div><div><p className="text-[9px] tracking-[.25em] opacity-50 mb-5">ABOUT</p><button onClick={()=>go('about')} className="block text-sm mb-2">Our Story</button><button className="block text-sm mb-2">Craftsmanship</button><button className="block text-sm">Contact</button></div></div><div className="mt-24 border-t border-white/15 pt-8 flex flex-col md:flex-row justify-between gap-5 text-[9px] tracking-[.2em] opacity-50"><span>© 2026 RESPECT COLLECTION</span><span>PRIVACY · TERMS · CLIENT SERVICES</span></div></footer>
 <AnimatePresence>{search&&<Overlay onClose={()=>setSearch(false)}><div className="w-full max-w-4xl"><p className="text-[9px] tracking-[.25em] opacity-50 mb-4">SEARCH RESPECT COLLECTION</p><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, collections..." className="w-full bg-transparent border-b border-black/30 py-4 text-4xl md:text-6xl serif outline-none"/><div className="mt-10 grid grid-cols-2 md:grid-cols-4 gap-3">{visible.slice(0,4).map(p=><button key={p.id} onClick={()=>{setSearch(false);setQuick(p)}} className="text-left"><img src={p.image} className="aspect-[3/4] object-cover"/><p className="text-xs mt-3">{p.name}</p></button>)}</div></div></Overlay>}{bagOpen&&<Drawer onClose={()=>setBagOpen(false)} bag={bag} products={products} setBag={setBag}/>} {quick&&<Quick p={quick} onClose={()=>setQuick(null)} onAdd={()=>{add(quick);setQuick(null)}}/>}</AnimatePresence>
 </main>
}
function Category({img,title,label,reverse,onClick}:{img:string;title:string;label:string;reverse?:boolean;onClick:()=>void}){return <section className={`grid md:grid-cols-2 min-h-[72vh] ${reverse?'md:[&>*:first-child]:order-2':''}`}><div className="image-wrap"><img src={img} className="w-full h-full min-h-[50vh] object-cover"/></div><div className="flex flex-col justify-center px-8 md:px-20 py-20"><p className="text-[9px] tracking-[.28em] text-black/45">{label}</p><h2 className="serif text-5xl md:text-6xl mt-5 max-w-lg">{title}</h2><button onClick={onClick} className="mt-9 w-fit text-[10px] tracking-[.2em] border-b border-black pb-2">SHOP {label}</button></div></section>}
function ProductCard({p,wish,onWish,onQuick,onAdd}:{p:Product;wish:boolean;onWish:()=>void;onQuick:()=>void;onAdd:()=>void}){return <article className="group"><div className="relative image-wrap bg-[#e8e4db]"><img src={p.image} className="w-full aspect-[3/4] object-cover group-hover:opacity-0"/><img src={p.secondary} className="absolute inset-0 w-full h-full object-cover opacity-0 group-hover:opacity-100"/><button onClick={onWish} aria-label="Wishlist" className="absolute top-4 right-4"><Heart size={16} fill={wish?'currentColor':'none'}/></button><button onClick={onQuick} className="absolute bottom-0 left-0 right-0 bg-[#f4f1ea]/95 py-4 text-[9px] tracking-[.2em] translate-y-full group-hover:translate-y-0 transition">QUICK VIEW</button></div><div className="pt-4 pb-7"><div className="flex justify-between gap-2"><div><p className="text-sm">{p.name}</p><p className="text-[10px] text-black/45 mt-1">{p.collection}</p></div><p className="text-xs">{money(p.price)}</p></div><button onClick={onAdd} className="mt-3 text-[9px] tracking-[.2em] opacity-0 group-hover:opacity-100 transition border-b border-black">ADD TO BAG</button></div></article>}
function Collection({title,subtitle,hero,filter,setFilter,products,onQuick,onAdd,wishlist,setWishlist}:{title:string;subtitle:string;hero:string;filter:string;setFilter:(x:string)=>void;products:Product[];onQuick:(p:Product)=>void;onAdd:(p:Product)=>void;wishlist:string[];setWishlist:(x:string[])=>void}){return <section className="pt-[76px]"><div className="relative h-[55vh] overflow-hidden"><img src={hero} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-black/25"/><div className="relative z-10 h-full flex flex-col justify-end text-white p-7 md:p-14"><p className="text-[9px] tracking-[.3em]">RESPECT COLLECTION</p><h1 className="serif text-6xl md:text-8xl mt-4">{title}</h1><p className="mt-4 text-sm opacity-80">{subtitle}</p></div></div><div className="px-6 md:px-12 py-10"><div className="flex gap-6 border-b border-black/10 pb-5 overflow-x-auto text-[9px] tracking-[.2em]">{['All','Watches','Men','Women','Bags','Fragrance'].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'border-b border-black pb-2':''}>{x.toUpperCase()}</button>)}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-x-3 pt-8">{products.map(p=><ProductCard key={p.id} p={p} wish={wishlist.includes(p.id)} onWish={()=>setWishlist(wishlist.includes(p.id)?wishlist.filter(x=>x!==p.id):[...wishlist,p.id])} onQuick={()=>onQuick(p)} onAdd={()=>onAdd(p)}/>)}</div></div></section>}
function Overlay({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-[#f4f1ea] p-6 md:p-12 overflow-auto"><button onClick={onClose} className="absolute top-7 right-7"><X/></button><div className="min-h-full flex items-center justify-center">{children}</div></motion.div>}
function Drawer({onClose,bag,products,setBag}:{onClose:()=>void;bag:string[];products:Product[];setBag:(x:string[])=>void}){return <motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.5,ease:[.2,.7,.2,1]}} className="fixed right-0 top-0 bottom-0 z-50 w-full sm:max-w-md bg-[#f4f1ea] p-7 shadow-2xl overflow-auto"><div className="flex justify-between"><p className="text-[10px] tracking-[.25em]">YOUR BAG · {bag.length}</p><button onClick={onClose}><X size={18}/></button></div>{bag.length===0?<div className="h-[80vh] flex items-center justify-center"><p className="serif text-3xl">Your bag is quiet.</p></div>:<><div className="mt-12 space-y-6">{bag.map((id,i)=>{const p=products.find(x=>x.id===id)!;return <div key={i} className="flex gap-4 border-b border-black/10 pb-5"><img src={p.image} className="w-24 h-28 object-cover"/><div className="flex-1"><p className="text-sm">{p.name}</p><p className="text-xs mt-2">{money(p.price)}</p><button onClick={()=>setBag(bag.filter((_,j)=>j!==i))} className="text-[9px] tracking-[.15em] mt-5 underline">REMOVE</button></div></div>})}</div><div className="mt-10 border-t border-black/20 pt-5 flex justify-between"><span>SUBTOTAL</span><span>{money(bag.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0))}</span></div><button className="mt-6 w-full bg-[#11110f] text-white py-5 text-[10px] tracking-[.2em]">PROCEED TO CHECKOUT</button><button onClick={onClose} className="mt-4 w-full border border-black/20 py-5 text-[10px] tracking-[.2em]">CONTINUE SHOPPING</button></>}</motion.aside>}
function Quick({p,onClose,onAdd}:{p:Product;onClose:()=>void;onAdd:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/40 p-4 md:p-12 flex items-center justify-center" onClick={onClose}><motion.div initial={{y:25}} animate={{y:0}} className="bg-[#f4f1ea] max-w-4xl w-full grid md:grid-cols-2" onClick={e=>e.stopPropagation()}><div className="image-wrap"><img src={p.image} className="w-full h-full min-h-[55vh] object-cover"/></div><div className="p-8 md:p-12 flex flex-col"><button onClick={onClose} className="ml-auto"><X size={18}/></button><p className="text-[9px] tracking-[.25em] text-black/45 mt-10">{p.collection}</p><h2 className="serif text-5xl mt-3">{p.name}</h2><p className="mt-5 text-sm leading-6 text-black/60">{p.description}</p><p className="mt-7">{money(p.price)}</p><div className="mt-auto"><button onClick={onAdd} className="w-full bg-[#11110f] text-white py-5 text-[10px] tracking-[.2em]">ADD TO BAG</button><button onClick={onClose} className="w-full py-5 text-[10px] tracking-[.2em]">VIEW PRODUCT</button></div></div></motion.div></motion.div>}
